### ISSUE TITLE
Touch reporting is 20ish degrees off CCW

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Swadge-IDF-5.0#134]
**Description**
_A clear and concise description of what the bug is._
When I move my finger to the "top" of the touchpad as defined by the orientation of the screen, the reported location is roughly 20 degrees off.

**Expected behavior**
_A clear and concise description of what you expected to happen._
Vectors should appear to be aligned with the screen

**Reproduction Steps**
_Steps to reproduce the behavior and how often it occurs._
Use Gamepad on latest `gamepad` branch

**Comment by AEFeinstein** [comment]
Closed by #139
