### ISSUE TITLE
Remove Sokoban

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Swadge-IDF-5.0#136]
Remove the mode

**Comment by Brycey92** [comment]
Are we moving soko to a graveyard folder for easy access/continuation next year, or should it go in a branch?

**Comment by AEFeinstein** [comment]
I'm scrubbing it from `main` and leaving the two branches around. Even if we opt to delete the branches as well, they can always be found at:
* https://github.com/AEFeinstein/Swadge-IDF-5.0/commit/2d5bd8ea5e71cc84302e3198e7012722436caf61
* https://github.com/AEFeinstein/Swadge-IDF-5.0/commit/6c72e1a41f0016e75ca8c8e41dc6e25bc97adc67
