### ISSUE TITLE
Racer Mode

### ISSUE THREAD

**Issue by jt-moriarty** [AEFeinstein/Swadge-IDF-5.0#16]
I will be making a racer mode leaning heavily on SNES F Zero as a starting point.

**Comment by AEFeinstein** [comment]
@jt-moriarty any anything on this?

**Comment by jt-moriarty** [comment]
Not as of yet, but I'm hoping to put some work in on it this weekend and report progress at this week's meeting.

**Comment by AEFeinstein** [comment]
For next year
