### ISSUE TITLE
Reorder items in main menu and Jukebox

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Swadge-IDF-5.0#163]
I know @AEFeinstein said he wanted to reorder menu items, especially putting Magtroid Pocket on top since it's the game that matches the theme.

@arty01238 and I can rearrange Jukebox's categories after the main menu gets done.

**Comment by AEFeinstein** [comment]
Already did the main menu in 608a1dd74a1482b240deaed26af4f584d682fa5b
Feel free to reorder Jukebox to match

**Comment by AEFeinstein** [comment]
And run `make format` on Jukebox afterwards
