### ISSUE TITLE
Port Tunernome

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Swadge-IDF-5.0#17]
**Summary**
_What is the feature all about? Is it a game, a utility, an enhancement, or something else?_
Tunernome, now in IDF 5.0!

**How to Test**
How can we verify the feature is working?
Run side-by-side with a 2023 Swadge

**Comment by AEFeinstein** [comment]
JSYK I had to tweak this a tad to be stereo buzzer friendly
