### ISSUE TITLE
Memory/Save/Data Manager

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Swadge-IDF-5.0#20]
**Summary**
_What is the feature all about? Is it a game, a utility, an enhancement, or something else?_
Memory manager from the 2023 1.1 update, but with per-mode namespaces

**Technical Spec**
_How will this be implemented?_
_What peripherals will be used, and how?_
In 2023, all accesses to NVS used the same namespace. With different namespaces, we can create a polished save manager, and can more easily reset single modes' data when they misbehave.

Wish list item: Inter-swadge communication

**Comment by AEFeinstein** [comment]
> when they misbehave

Pfft, they won't

**Comment by Brycey92** [comment]
It was decided this mode is not needed, and individual modes should make their own data reset/management as-needed case-by-case.

**Comment by AEFeinstein** [comment]
Yep, my game as a 'reset data' option on the menu, and a second menu level as confirmation :)
