### ISSUE TITLE
Handshake tool

### ISSUE THREAD

**Issue by emilyanthony4244** [AEFeinstein/Swadge-IDF-5.0#21]
Create a tool called Handshake to meet new swadges on site

get otherMac with p2pConnection
compare to mac address list stored
    add to list if not present
    ++ticker

ESP-NOW does have the peer lists functions but we need p2p connection to get the peers mac address so we probably wouldn't use this

Have silly sprites for milestones for number of swadges are met (5, 10, 42, 69 etc)

I can probably do this

**Comment by AEFeinstein** [comment]
You can definitely do this. I'd also like to see this used to pass high scores between games, and I don't think it would be too hard. I'm thinking you add two new function pointers to the [swadge mode struct](https://adam.feinste.in/Swadge-IDF-5.0/structswadgeMode__t.html#pub-attribs):
1. A function which is called before handshaking to get a blob of data that gets built into the handshake packet (or packets if it gets big I suppose)
2. A function which is called after handshaking to recieve a blob of data from some other swadge

You wouldn't be responsible for the blobs, you'd just have to concatenate them before sending and split them up after receiving. Not too bad, right? Each mode author would be responsible for their own blob.
