### ISSUE TITLE
Gameshow Mode for VR Chat Integration

### ISSUE THREAD

**Issue by jt-moriarty** [AEFeinstein/Swadge-IDF-5.0#22]
**Summary**
_What is the feature all about? Is it a game, a utility, an enhancement, or something else?_
A request for VR Chat integration that facilitates communication between swadge users and VR chat visitors

Allow for ABC outputs from swadge sent to VR chat for implementing things like simple Jackbox games?
Allow for hosts in VR chat to potentially send messages to swadge users or specific swadges, host can view connected swadges?

This was a request for the VR Chat Portal crew, ask Charles for exact point of contact.

**Comment by AEFeinstein** [comment]
Closed for next year
