### ISSUE TITLE
Quick Settings Menu

### ISSUE THREAD

**Issue by dylwhich** [AEFeinstein/Swadge-IDF-5.0#28]
**Summary**
_What is the feature all about? Is it a game, a utility, an enhancement, or something else?_

A settings menu that can be easily called up in the middle of a mode by, for example, holding Start.

This would be a smaller menu than the main menu, maybe even including big icons, that allows the user to quickly change global settings, mainly:
* BGM Mute
* SFX Mute
* LED Brightness
* Screen Brightness
* "Panels Mode" - A quick setting to fully mute and set the LED brightness very low or off

Assuming there's enough room, screensaver and mic gain could also go there.

**Technical Spec**
_How will this be implemented?_
_What peripherals will be used, and how?_

This could be implemented in at least a couple ways:

**A: Completely transparently to the swadge mode:**
Similar to how the "hold select to exit" feature works, the swadge main loop itself would detect the menu being activated. It would work like this:

1. The user holds START, or does something else to activate the quick menu
2. The main loop sets up the quick settings menu
3. The quick settings menu saves the framebuffer into SPIRAM
4. The main loop sets a flag indicating the quick settings menu is active
5. When handling input events, the main loops now sends them to the quick menu instead of the swadge mode
6. When drawing the screen, main loop now calls the quick menu's main loop callback instead of the swadge mode's
7. The quick menu's main loop callback would draw a full-screen settings menu, over top of a dimmed version of the saved framebuffer, sort of like a phone's notification drawer or something
8. When the user exits the quick menu, the flag is cleared
9. The quick settings menu draws the framebuffer back to the screen from SPIRAM
10. The original mode's callbacks are used again instead of the quick menu

Pros:
* Zero effort to add to any swadge mode
* 100% consistent across every mode
* Completely removes need for mode developers to think about global settings or dedicate precious buttons to muting/LED brightness.
* If expanded slightly, this system could be reused to add other "enhancements" to swadge modes without needing to code for it specifically in the swadge mode. An automatic screensaver or background light dances would be another good option for this sort of implementation.

Cons:
* A bit harder to implement
* Might be hard to avoid time jumps affecting the swadge mode still
* Maybe a bit less flexible
* Allowing modes to add their own options to the menu might be a bit more involved

**Cooperatively with the mode**
This would work as an extension the swadge mode would have to actively support, just like the current menus

1. The mode detects that the user wants to open the quick settings menu, however it decides
2. The mode sets a flag to say it's on the quick settings menu
3. When the mode's main loop is called, it checks that flag and calls the quick settings menu main loop callback instead
4. When the mode receives input, it checks the flag and calls the quick settings menu input function instead
5. When the user exits the quick settings menu, the mode clears the flag and resumes as normal.

Pros:
* Less complicated to implement
* Would work just like existing menus
* Would be pretty easy for each mode to add a couple settings of its own
* Maybe adding to each mode individually will decrease the likelihood of the transparent implementation causing bugs with modes that do weird stuff?

Cons:
* Adds a bit more complexity to every swadge mode that uses it
* Would not necessarily be consistent across modes

**UI**
_What are the display screens & menus (if applicable)?_
_What user inputs are there for each screen?_

**Mockups**
_Paste any mockups of screens or anything else here._

**How to Test**
How can we verify the feature is working?

Try it once on each screen in each mode and make sure it works as expected.

**Comment by AEFeinstein** [comment]
I like the "Completely transparently to the swadge mode" implementation a lot more. Seems like you'd just have to hot swap `cSwadgeMode`. As long as you don't call `cSwadgeMode->fnMainLoop()` with some insane value when the menu closes (and the mode isn't checking system ticks) it should be oblivious to the pause.

Also note that there already is a framebuffer, so as long as you don't do a full screen clear, you can draw over it as you please. Just leave a margin so the mode can 'peek' out from under the settings. I think it's reasonable to expect each mode to redraw the screen each frame.
