### ISSUE TITLE
Settings Menu Items With Options

### ISSUE THREAD

**Issue by dylwhich** [AEFeinstein/Swadge-IDF-5.0#33]
**Summary**
_What is the feature all about? Is it a game, a utility, an enhancement, or something else?_

An enhancement to the settings and/or menu interfaces to support settings that aren't just a simple value in a range.

For example, the screensaver setting isn't quite a plain number of seconds, since it should only really be set to a few values within a wide range (e.g. 0, 10, 15, 30, 60, 120, 300) and not in a simple incremental pattern (e.g. 0, 5, 10, 15, 20, ...).

We can add a menu item style that has a list of labels as well as values to give human-readable descriptions to go with actual settings values.

**Technical Spec**
_How will this be implemented?_
_What peripherals will be used, and how?_

In `menu.h` / `menu.c` two new functions would be added to support these new menu item types. The first, to add an item, would behave almost as a combination of the multi-item and the regular setting item, needing both a list of label options and a pointer to the setting bounds, but it would also need a list of actual settings values the same size as the options list.

When the callback is called, the callback will send the selected option as well as the corresponding setting value for that option.

**UI**
_What are the display screens & menus (if applicable)?_
_What user inputs are there for each screen?_

In `menuLogbookRenderer.c`, these new settings would be displayed in the same manner as normal menu items with options.

**Mockups**
_Paste any mockups of screens or anything else here._

**How to Test**
How can we verify the feature is working?

Update the existing screensaver setting to use the mapped settings item implementation and verify that it still allows the screensaver setting to be stored and retrieved.

**Comment by AEFeinstein** [comment]
This all makes sense. I think the planned `addLabeledSettingsItemToMenu()` would need the labels as an array, the values also as an array, the length (which acts as a bound), and the current index.
