### ISSUE TITLE
Finish Full-Motion Branch

### ISSUE THREAD

**Issue by cnlohr** [AEFeinstein/Swadge-IDF-5.0#55]
Three major features remain:

- [ ] Auto cal anti-drift.
- [ ] Make motion controls an actual thing in Swadges.
- [ ] Convert to integer math from float.
- [ ] Figure out why I2C bus sometimes gives this error: `E (713358) i2c: i2c_master_read(1328): i2c data read length error`

**Comment by cnlohr** [comment]
Correct.  That is the plan.  I could turn it into a component immediately but it's not "done" yet.

**Comment by AEFeinstein** [comment]
Done in #102
