### ISSUE TITLE
Pushy Kawaii Go: Multiple of same effect not applied

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Swadge-IDF-5.0#89]
**Description**
_A clear and concise description of what the bug is._
In Pushy Kawaii Go, multiple `69`s don't have effects applied to more than one set. No testing done with multiple `420`s but same bug is suspected.

**Expected behavior**
_A clear and concise description of what you expected to happen._
Each instance of the meme numbers should have their respective effects applied, no matter how many times they appear on the score counter.

**Reproduction Steps**
_Steps to reproduce the behavior and how often it occurs._
Get to score `6969` somehow, such as setting the score on mode start, or by "gittin' gud".

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Logs**
_If applicable, add logs from when the problem occurred._

**Affected Version**
 - Platform: [Windows, Linux, and/or Firmware] All versions
 - git branch: [e.g. `main`] `main`
 - git hash: [e.g. a2a1a77 ] c9c7a8092725ba4d892194d76c1d335ae0e5fbb0

**Additional Notes**
_Add any other notes about the problem_
The bug lies somewhere in or near the `checkRainbow` and `checkWeed` functions, as I rewrote them to use more standard c library methods.

**Comment by AEFeinstein** [comment]
The root function is:
```c
static void checkSubStr(char const* counterStr, char const* const subStr, bool digitBitmap[NUM_DIGITS], int64_t* timer)
{
    memset(digitBitmap, false, NUM_DIGITS);

    char const* subStrInCounterStr = strstr(counterStr, subStr);
    if (subStrInCounterStr == NULL)
    {
        *timer = EFFECT_MAX;
        return;
    }

    uint8_t startDigit = subStrInCounterStr - counterStr;
    for (uint8_t i = 0; i < strlen(subStr); i++)
    {
        digitBitmap[startDigit + i] = true;
    }

    *timer = 0;
}
```
The issue seems to be that [`strstr()`](https://man7.org/linux/man-pages/man3/strstr.3.html) only finds the first occurrence of the substring in the string and this function doesn't have a loop of any kind. You want some sort of `while` loop here that continues to search if a substring is found and adjusts the string pointer to search after the previously found substring on the next iteration.

Totally untested stab at it:
```c
static void checkSubStr(char const* counterStr, char const* const subStr, bool digitBitmap[NUM_DIGITS], int64_t* timer)
{
    bool found = false;
    memset(digitBitmap, false, NUM_DIGITS);

    char const* subStrInCounterStr = strstr(counterStr, subStr);
    while(NULL != subStrInCounterStr)
    {
        uint8_t startDigit = subStrInCounterStr - counterStr;
        for (uint8_t i = 0; i < strlen(subStr); i++)
        {
            digitBitmap[startDigit + i] = true;
        }

        *timer = 0;
        found = true;

        // Move counterStr to be one after the found str
        counterStr = &subStrInCounterStr[1];
        // continue searching
        subStrInCounterStr = strstr(counterStr, subStr);
    }

    if(!found)
    {
        *timer = EFFECT_MAX;
    }
}
```

**Comment by Brycey92** [comment]
Oddly, I could have sworn I had a while loop. It may have only been in my other branch for making the video, though. In any case, thanks for the help! With a couple of tweaks, your code works.

**Comment by AEFeinstein** [comment]
Glad it was close enough!
