### ISSUE TITLE
Verify Tunernome is still correctly tuned

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Swadge-IDF-5.0#91]
**Summary**
_What is the feature all about? Is it a game, a utility, an enhancement, or something else?_
We've been through many microphones over the years, and need to make sure Tunernome is still hearing the frequencies we think it is.
I could use your help @cnlohr since you wrote the underlying colorchord, and/or someone to help play music that they know is in-tune.

**Technical Spec**
_How will this be implemented?_
_What peripherals will be used, and how?_

**UI**
_What are the display screens & menus (if applicable)?_
_What user inputs are there for each screen?_

**Mockups**
_Paste any mockups of screens or anything else here._

**How to Test**
How can we verify the feature is working?

**Comment by AEFeinstein** [comment]
Checked out
https://magfest.slack.com/archives/C6FNXU6KX/p1700607071726109
