### ISSUE TITLE
Add instruments to Tunernome

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Swadge-IDF-5.0#92]
**Summary**
_What is the feature all about? Is it a game, a utility, an enhancement, or something else?_
Since we're bringing Tunernome over from last year, I want to add something to it. The easiest thing to add is an instrument. We can even add several.

**Technical Spec**
_How will this be implemented?_
_What peripherals will be used, and how?_
All the arrays for implementing instruments are near the top of `tunernome.c`. Each group of arrays needs to be added to.

**UI**
_What are the display screens & menus (if applicable)?_
_What user inputs are there for each screen?_

**Mockups**
_Paste any mockups of screens or anything else here._

**How to Test**
How can we verify the feature is working?

**Comment by AEFeinstein** [comment]
Or didgeridon't
